export const EVENTS = {
  STATUS_CHANGED: "STATUS_CHANGED",
  GOOGLE_JUMPED: "GOOGLE_JUMPED",
  GOOGLE_ESCAPED: "GOOGLE_ESCAPED",
  PLAYER_MOVED: "PLAYER_MOVED",
  PLAYER_NAME_WAS_CHANGED: "PLAYER_NAME_WAS_CHANGED",
  GOOGLE_WAS_CAUGHT: "GOOGLE_WAS_CAUGHT",
  GAME_END: "GAME_END",
};
